const common = {
  timeline: "Self-directed product study",
  team: "Independent product designer",
  constraints: ["No access to production analytics", "Assumptions require validation with real users", "Balance clarity with the product’s domain complexity"],
  research: ["Comparative product review", "Task and journey mapping", "Heuristic evaluation", "Hypothesis and assumption mapping"],
  accessibility: ["Hierarchy and status do not rely on color alone", "Readable type, visible focus, and 44px minimum targets", "Semantic structure and clear control labels", "Reduced-motion behavior for nonessential animation"],
};

const featured = {
  "punjab-pagri-house": {
    timeline: "End-to-end client project",
    team: "Business owner · Product Design Lead · AI-assisted development",
    businessGoal: "Create a credible online discovery and sales channel while preserving the business’s cultural identity.",
    userProblem: "Customers need to understand unfamiliar product categories and choose with confidence on mobile.",
    constraints: ["Balance cultural storytelling with direct shopping", "Support first-time and knowledgeable buyers", "Create a maintainable catalogue system"],
    research: ["Catalogue and content audit", "Competitive commerce review", "Customer-question mapping", "Terminology and feasibility checks with the owner"],
    insights: ["Cultural context increases purchase confidence.", "Categories must work for customers with different product knowledge.", "Trust information must appear before checkout—not only at the end."],
    journey: ["Discover", "Understand categories", "Compare", "Inspect details", "Build trust", "Purchase or contact"],
    ia: ["Home", "Shop", "Category", "Product detail", "Cultural guidance", "Cart / checkout", "Support"],
    decisions: [
      ["Products lead; story supports", "A story-first page delayed the primary shopping task.", "Less heritage content above the fold; richer context appears near decisions."],
      ["Familiar commerce patterns", "Customers already face product-learning cost.", "The interaction model is intentionally conventional so products carry the personality."],
      ["Compact mobile comparison", "Opening every item creates unnecessary effort.", "Cards show only decision-critical information."],
    ],
    iterations: ["Reduced competing homepage messages.", "Simplified categories and strengthened grouping.", "Adjusted mobile card density and image behavior."],
    collaboration: "As Product Design Lead, I curated the idea into a real-world product and directed the end-to-end experience. I used AI as an execution accelerator for exploration, implementation support, and quality checks while retaining ownership of product decisions, UX direction, requirements, and final delivery. Handoff covered reusable components, responsive states, content rules, and edge cases.",
    designSystem: "A compact system for typography, spacing, buttons, product cards, forms, imagery, and commerce states.",
    responsive: "Mobile prioritizes product recognition and direct actions. Larger screens add comparison density and supporting context without changing task order.",
    metrics: [["Launch status", "Live", "Verified"], ["Device coverage", "Mobile + desktop", "Verified"], ["Conversion impact", "Not yet instrumented", "Unknown"]],
    lessons: ["Education and conversion are part of the same journey.", "Familiar patterns can make room for a distinctive brand.", "Analytics planning must happen before launch."],
    next: "Instrument category findability, product engagement, add-to-cart rate, and checkout completion.",
  },
  "apricus-academy": {
    timeline: "Idea-to-product development · Soon to be live",
    team: "Product Design Lead · AI-assisted development",
    businessGoal: "Increase meaningful course discovery and continuation by making progress and next steps visible.",
    userProblem: "Students need to choose courses, resume learning, and understand progress across disconnected tasks.",
    insights: ["The next action matters more than total information.", "Progress needs context, not only a percentage.", "Discovery and active learning need different information modes."],
    journey: ["Explore", "Evaluate fit", "Enroll", "Resume", "Complete milestones", "Review progress"],
    ia: ["Discover", "Course detail", "Enrollment", "My learning", "Lesson", "Progress"],
    decisions: [["Action-led dashboard", "Content-heavy dashboards increase planning effort.", "Deep analytics move one level down."], ["Separate discovery and learning", "Choosing and completing require different information.", "One additional destination creates clearer mental models."], ["Quiet progress cues", "Excessive gamification can distract from learning.", "The experience is less playful but more purposeful."]],
    iterations: ["Reduced dashboard modules.", "Reworked course cards around decision attributes.", "Moved achievements below active commitments."],
    collaboration: "As Product Design Lead, I curated the initial idea into a real-world product direction and led the experience from product framing through delivery. AI supported exploration, implementation, and iteration under my direction; I remained responsible for requirements, UX decisions, system behavior, quality, and final product coherence. Before launch, course content models, completion events, empty states, and progress logic will be aligned and verified.",
    designSystem: "Reusable course cards, progress indicators, navigation states, action hierarchy, and learning containers.",
    responsive: "Mobile emphasizes resuming a lesson; desktop supports comparison and a wider progress overview.",
    metrics: [["Course continuation", "Target metric", "Target"], ["Time to resume lesson", "Target metric", "Target"], ["Measured impact", "Not available", "Unknown"]],
    lessons: ["Concept work must state uncertainty.", "Progress UI depends on a reliable event model.", "The next research step is part of the design outcome."],
    next: "Interview learners and test course comparison and resume-learning tasks before increasing fidelity.",
  },
  "excellence-university": {
    businessGoal: "Help more students complete valid schedules with fewer avoidable errors and support requests.",
    userProblem: "Students must compare requirements, availability, deadlines, and conflicts during consequential decisions.",
    constraints: ["Represent policy complexity without exposing system complexity", "Make automated recommendations explainable", "Support high-stress, time-sensitive decisions"],
    insights: ["Conflict messages must enable recovery.", "Eligibility belongs near selection.", "Deadlines and blocked tasks should shape priority."],
    journey: ["Review requirements", "Discover", "Compare sections", "Build schedule", "Resolve conflicts", "Confirm"],
    ia: ["Dashboard", "Requirements", "Catalogue", "Course detail", "Schedule builder", "Conflict resolution", "Confirmation"],
    decisions: [["Detect conflicts early", "Late errors waste effort and increase stress.", "More system states must be explained during selection."], ["Explain alternatives", "Recommendations need understandable reasons.", "Explanations add density but improve trust."], ["Task-based navigation", "Students arrive to complete actions.", "Administrative ownership is less prominent."]],
    iterations: ["Moved prerequisite warnings earlier.", "Changed conflict resolution from a dead-end modal to inline comparison.", "Elevated time-sensitive actions."],
    collaboration: "A build requires engineering and academic-operations alignment on rule precedence, latency, conflict states, and fallbacks when recommendations fail.",
    designSystem: "Academic statuses, warnings, course cards, schedule blocks, conflict explanations, and action states use consistent semantics.",
    responsive: "Mobile supports status checks and focused changes; dense schedule comparison progressively expands on larger screens.",
    metrics: [["Valid schedule completion", "Target metric", "Target"], ["Enrollment support requests", "Reduction target", "Target"], ["Measured impact", "Not available", "Unknown"]],
    lessons: ["Automation must be understandable and overridable.", "Error prevention belongs inside the journey.", "Institutional workflows require policy stakeholders."],
    next: "Validate rules with academic staff and test conflict comprehension and recovery with students.",
  },
};

export function getStory(project) {
  const detail = featured[project.id] || {};
  return {
    ...common,
    businessGoal: "Improve comprehension and task completion through clearer product hierarchy.",
    userProblem: project.challenge,
    insights: ["The most important information should match the next user decision.", "Progressive disclosure can preserve depth without equal visual weight.", "Outcomes require validation; interface quality alone is not evidence."],
    journey: ["Orient", "Understand", "Decide", "Act", "Confirm"],
    ia: ["Overview", "Primary task", "Detail", "History", "Settings"],
    decisions: [[project.approach, "The initial experience exposed complexity before establishing priority.", "Secondary information requires an additional action."]],
    iterations: ["Reduced competing information.", "Strengthened action hierarchy.", "Documented empty, error, and responsive states."],
    collaboration: "A production phase would begin with data, content, feasibility, states, and acceptance criteria—not a final-screen handoff.",
    designSystem: "Reusable hierarchy, spacing, navigation, action, card, status, and feedback patterns.",
    responsive: "The task order remains consistent; density and supporting context progressively increase with available space.",
    metrics: [["Primary outcome", "Not measured", "Unknown"], ["Usability benchmark", "Task completion target", "Target"]],
    lessons: ["A polished concept is a hypothesis until it reaches users.", "Metrics must be planned before implementation."],
    next: "Test the primary journey with representative users and define instrumentation with product and engineering.",
    ...detail,
  };
}
