const common = {
  timeline: "Self-directed product study",
  team: "Independent product designer",
  constraints: ["No access to production analytics", "Assumptions require validation with real users", "Balance clarity with the product’s domain complexity"],
  research: ["Comparative product review", "Task and journey mapping", "Heuristic evaluation", "Hypothesis and assumption mapping"],
  accessibility: ["Hierarchy and status do not rely on color alone", "Readable type, visible focus, and 44px minimum targets", "Semantic structure and clear control labels", "Reduced-motion behavior for nonessential animation"],
};

const featured = {
  "punjab-pagri-house": {
    timeline: "End-to-end client project",
    team: "Business owner · AI Product Builder & Product Designer",
    businessGoal: "Create a credible online discovery and sales channel while preserving the business’s cultural identity.",
    userProblem: "Customers need to understand unfamiliar product categories and choose with confidence on mobile.",
    constraints: ["Balance cultural storytelling with direct shopping", "Support first-time and knowledgeable buyers", "Create a maintainable catalogue system"],
    research: ["Catalogue and content audit", "Competitive commerce review", "Customer-question mapping", "Terminology and feasibility checks with the owner"],
    insights: ["Cultural context increases purchase confidence.", "Categories must work for customers with different product knowledge.", "Trust information must appear before checkout—not only at the end."],
    journey: ["Discover", "Understand categories", "Compare", "Inspect details", "Build trust", "Purchase or contact"],
    ia: ["Home", "Shop", "Category", "Product detail", "Cultural guidance", "Cart / checkout", "Support"],
    decisions: [
      ["Products lead; story supports", "A story-first page delayed the primary shopping task.", "Less heritage content above the fold; richer context appears near decisions."],
      ["Familiar commerce patterns", "Customers already face product-learning cost.", "The interaction model is intentionally conventional so products carry the personality."],
      ["Compact mobile comparison", "Opening every item creates unnecessary effort.", "Cards show only decision-critical information."],
    ],
    iterations: ["Reduced competing homepage messages.", "Simplified categories and strengthened grouping.", "Adjusted mobile card density and image behavior."],
    collaboration: "As the AI Product Builder and Product Designer, I transformed the idea into a real-world product and directed the complete experience from strategy through delivery. I used AI to accelerate exploration, implementation, and quality checks while retaining ownership of the product decisions, UX direction, requirements, and final outcome. Handoff covered reusable components, responsive states, content rules, and edge cases.",
    designSystem: "A compact system for typography, spacing, buttons, product cards, forms, imagery, and commerce states.",
    responsive: "Mobile prioritizes product recognition and direct actions. Larger screens add comparison density and supporting context without changing task order.",
    metrics: [["Launch status", "Live", "Verified"], ["Device coverage", "Mobile + desktop", "Verified"], ["Conversion impact", "Not yet instrumented", "Unknown"]],
    lessons: ["Education and conversion are part of the same journey.", "Familiar patterns can make room for a distinctive brand.", "Analytics planning must happen before launch."],
    next: "Instrument category findability, product engagement, add-to-cart rate, and checkout completion.",
  },
  "apricus-academy": {
    timeline: "Idea-to-product development · Soon to be live",
    team: "AI Product Builder & Product Designer",
    businessGoal: "Give Apricus Academy one secure, premium system for delivering and managing NCLEX classes, assessments, and tests while creating a scalable foundation for future programs.",
    userProblem: "NCLEX students need a reliable place to access recorded classes, complete assessments, and take tests whenever and wherever they study, without moving between disconnected tools.",
    constraints: ["Keep classes, assessments, and tests simple across desktop and mobile", "Associate every student with a unique licence and the correct permissions", "Deliver recorded classes quickly and securely through Google Drive", "Support NCLEX workflows without limiting future course expansion"],
    research: ["NCLEX learning and assessment journey mapping", "LMS and exam-preparation pattern review", "Licence activation and access-state mapping", "Recorded-class delivery and responsive-flow evaluation"],
    insights: ["NCLEX preparation works best when lessons, practice assessments, and tests form one continuous journey.", "A unique licence creates a clear relationship between each student and their permitted content.", "Recorded classes must open quickly and reliably to make anytime learning feel genuinely premium.", "The platform architecture should support new programs without redesigning the core experience."],
    journey: ["Receive licence", "Activate secure access", "Open dashboard", "Attend or watch a class", "Complete an assessment", "Take a test", "Review progress"],
    ia: ["Sign in / licence activation", "Student dashboard", "Classes and recordings", "Assessments", "Tests", "Progress", "Account and access status"],
    decisions: [["One learning and assessment hub", "NCLEX students needed classes, assessments, and tests in one focused workflow.", "The dashboard requires disciplined hierarchy as more content is added."], ["Licence-based student access", "The academy needed to assign and manage learning access for each student individually.", "The system requires clear activation, invalid, used, and expired licence states."], ["Google Drive recorded-class delivery", "Integrated cloud delivery gives students fast access to recorded sessions while keeping content management practical for the academy.", "Permissions and unavailable-file states must remain synchronized with the LMS."], ["NCLEX-first, scalable architecture", "The initial experience must reflect the structure and intensity of NCLEX preparation.", "Reusable course, assessment, and test models are required to support other programs later."]],
    iterations: ["Reframed the dashboard around classes, upcoming assessments, and tests.", "Made licence and access status visible in the account experience.", "Simplified the path from sign-in to a recorded class through Google Drive integration.", "Standardized content structures so future programs can use the same platform foundation."],
    collaboration: "As the AI Product Builder and Product Designer, I shaped and developed the LMS from product framing through delivery. I defined the NCLEX learning journey, centralized class and assessment structure, responsive behavior, unique-licence system, and secure Google Drive integration for recorded content. I used AI to accelerate exploration, implementation, testing, and iteration while retaining ownership of requirements, UX decisions, system behavior, security-conscious access design, quality, and final product coherence.",
    designSystem: "A premium, focused system of class cards, video and lesson containers, assessment and test states, licence statuses, navigation, feedback, and responsive learning patterns.",
    responsive: "The core journey remains consistent across devices: activate a licence, open assigned classes, stream a recording, complete assessments, and take tests. Mobile prioritizes immediate access, readable learning content, and distraction-free exam interactions.",
    metrics: [["Classes + assessments + tests", "Unified platform", "Developed"], ["Recorded-class delivery", "Google Drive integrated", "Developed"], ["Licensed student access", "Unique + secure", "Developed"], ["Program architecture", "NCLEX-first + scalable", "Developed"], ["Measured impact", "Not yet available", "Unknown"]],
    lessons: ["Assessment management is part of the learning journey, not a separate utility.", "Secure access must remain clear and effortless for legitimate students.", "Fast recorded-class delivery is essential to a premium online-learning experience.", "Designing for NCLEX specificity and platform scalability can coexist through reusable content models."],
    next: "Validate licence recovery, recorded-class playback, assessment completion, and timed-test flows with NCLEX students before launch.",
  },
  "excellence-university": {
    businessGoal: "Help more students complete valid schedules with fewer avoidable errors and support requests.",
    userProblem: "Students must compare requirements, availability, deadlines, and conflicts during consequential decisions.",
    constraints: ["Represent policy complexity without exposing system complexity", "Make automated recommendations explainable", "Support high-stress, time-sensitive decisions"],
    insights: ["Conflict messages must enable recovery.", "Eligibility belongs near selection.", "Deadlines and blocked tasks should shape priority."],
    journey: ["Review requirements", "Discover", "Compare sections", "Build schedule", "Resolve conflicts", "Confirm"],
    ia: ["Dashboard", "Requirements", "Catalogue", "Course detail", "Schedule builder", "Conflict resolution", "Confirmation"],
    decisions: [["Detect conflicts early", "Late errors waste effort and increase stress.", "More system states must be explained during selection."], ["Explain alternatives", "Recommendations need understandable reasons.", "Explanations add density but improve trust."], ["Task-based navigation", "Students arrive to complete actions.", "Administrative ownership is less prominent."]],
    iterations: ["Moved prerequisite warnings earlier.", "Changed conflict resolution from a dead-end modal to inline comparison.", "Elevated time-sensitive actions."],
    collaboration: "A build requires engineering and academic-operations alignment on rule precedence, latency, conflict states, and fallbacks when recommendations fail.",
    designSystem: "Academic statuses, warnings, course cards, schedule blocks, conflict explanations, and action states use consistent semantics.",
    responsive: "Mobile supports status checks and focused changes; dense schedule comparison progressively expands on larger screens.",
    metrics: [["Valid schedule completion", "Target metric", "Target"], ["Enrollment support requests", "Reduction target", "Target"], ["Measured impact", "Not available", "Unknown"]],
    lessons: ["Automation must be understandable and overridable.", "Error prevention belongs inside the journey.", "Institutional workflows require policy stakeholders."],
    next: "Validate rules with academic staff and test conflict comprehension and recovery with students.",
  },
};

export function getStory(project) {
  const detail = featured[project.id] || {};
  return {
    ...common,
    businessGoal: "Improve comprehension and task completion through clearer product hierarchy.",
    userProblem: project.challenge,
    insights: ["The most important information should match the next user decision.", "Progressive disclosure can preserve depth without equal visual weight.", "Outcomes require validation; interface quality alone is not evidence."],
    journey: ["Orient", "Understand", "Decide", "Act", "Confirm"],
    ia: ["Overview", "Primary task", "Detail", "History", "Settings"],
    decisions: [[project.approach, "The initial experience exposed complexity before establishing priority.", "Secondary information requires an additional action."]],
    iterations: ["Reduced competing information.", "Strengthened action hierarchy.", "Documented empty, error, and responsive states."],
    collaboration: "A production phase would begin with data, content, feasibility, states, and acceptance criteria—not a final-screen handoff.",
    designSystem: "Reusable hierarchy, spacing, navigation, action, card, status, and feedback patterns.",
    responsive: "The task order remains consistent; density and supporting context progressively increase with available space.",
    metrics: [["Primary outcome", "Not measured", "Unknown"], ["Usability benchmark", "Task completion target", "Target"]],
    lessons: ["A polished concept is a hypothesis until it reaches users.", "Metrics must be planned before implementation."],
    next: "Test the primary journey with representative users and define instrumentation with product and engineering.",
    ...detail,
  };
}
